# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'shp_converter_mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QGraphicsView, QHBoxLayout, QLabel, QLineEdit,
    QListWidget, QListWidgetItem, QMainWindow, QMenu,
    QMenuBar, QPlainTextEdit, QProgressBar, QPushButton,
    QSizePolicy, QStatusBar, QTabWidget, QVBoxLayout,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(772, 883)
        self.actionWorkspace = QAction(MainWindow)
        self.actionWorkspace.setObjectName(u"actionWorkspace")
        self.actionDBF_Schema = QAction(MainWindow)
        self.actionDBF_Schema.setObjectName(u"actionDBF_Schema")
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.graphicsView = QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(0, 0, 771, 91))
        self.graphicsView.viewport().setProperty(u"cursor", QCursor(Qt.CursorShape.WaitCursor))
        self.graphicsView.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 100, 771, 671))
        self.tab_1 = QWidget()
        self.tab_1.setObjectName(u"tab_1")
        self.lblCircleSeg = QLabel(self.tab_1)
        self.lblCircleSeg.setObjectName(u"lblCircleSeg")
        self.lblCircleSeg.setGeometry(QRect(20, 360, 116, 16))
        self.lblCircleSeg.setStyleSheet(u"font: 600 9pt \"\ub098\ub214\uace0\ub515\";")
        self.lblFacilName = QLabel(self.tab_1)
        self.lblFacilName.setObjectName(u"lblFacilName")
        self.lblFacilName.setGeometry(QRect(20, 15, 121, 21))
        font = QFont()
        font.setFamilies([u"\ub098\ub214\uace0\ub515"])
        font.setPointSize(9)
        font.setWeight(QFont.DemiBold)
        font.setItalic(False)
        self.lblFacilName.setFont(font)
        self.lblFacilName.setStyleSheet(u"font: 600 9pt \"\ub098\ub214\uace0\ub515\";")
        self.btnStop = QPushButton(self.tab_1)
        self.btnStop.setObjectName(u"btnStop")
        self.btnStop.setGeometry(QRect(413, 550, 171, 31))
        self.btnStop.setStyleSheet(u"background-color: #f0f0f0;\n"
"border-color: rgb(255, 255, 255);")
        self.cmbExportFileFormat = QComboBox(self.tab_1)
        self.cmbExportFileFormat.setObjectName(u"cmbExportFileFormat")
        self.cmbExportFileFormat.setGeometry(QRect(150, 454, 281, 31))
        self.line = QFrame(self.tab_1)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(20, 156, 721, 20))
        self.line.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.cmbResamplingIntervals = QComboBox(self.tab_1)
        self.cmbResamplingIntervals.setObjectName(u"cmbResamplingIntervals")
        self.cmbResamplingIntervals.setGeometry(QRect(150, 387, 281, 31))
        self.btnApply = QPushButton(self.tab_1)
        self.btnApply.setObjectName(u"btnApply")
        self.btnApply.setGeometry(QRect(290, 125, 171, 31))
        self.btnApply.setStyleSheet(u"background-color: #f0f0f0;\n"
"border-color: rgb(255, 255, 255);")
        self.lblSaveFolder = QLabel(self.tab_1)
        self.lblSaveFolder.setObjectName(u"lblSaveFolder")
        self.lblSaveFolder.setGeometry(QRect(20, 87, 121, 21))
        self.lblSaveFolder.setStyleSheet(u"font: 600 9pt \"\ub098\ub214\uace0\ub515\";")
        self.lblSize = QLabel(self.tab_1)
        self.lblSize.setObjectName(u"lblSize")
        self.lblSize.setGeometry(QRect(20, 283, 116, 16))
        self.lblSize.setStyleSheet(u"font: 600 9pt \"\ub098\ub214\uace0\ub515\";")
        self.cmbSizeSelect = QComboBox(self.tab_1)
        self.cmbSizeSelect.setObjectName(u"cmbSizeSelect")
        self.cmbSizeSelect.setGeometry(QRect(150, 275, 281, 31))
        self.btnSaveFolderBrowse = QPushButton(self.tab_1)
        self.btnSaveFolderBrowse.setObjectName(u"btnSaveFolderBrowse")
        self.btnSaveFolderBrowse.setGeometry(QRect(620, 82, 121, 31))
        self.btnSaveFolderBrowse.setStyleSheet(u"background-color: #f0f0f0;")
        self.btnSaveFolderBrowse.setAutoDefault(False)
        self.line_2 = QFrame(self.tab_1)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(20, 310, 721, 20))
        self.line_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.line_2.setFrameShape(QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.lblStartDepth = QLabel(self.tab_1)
        self.lblStartDepth.setObjectName(u"lblStartDepth")
        self.lblStartDepth.setGeometry(QRect(20, 247, 116, 16))
        self.lblStartDepth.setStyleSheet(u"font: 600 9pt \"\ub098\ub214\uace0\ub515\";")
        self.lblExportFile = QLabel(self.tab_1)
        self.lblExportFile.setObjectName(u"lblExportFile")
        self.lblExportFile.setGeometry(QRect(20, 461, 116, 16))
        self.lblExportFile.setStyleSheet(u"font: 600 9pt \"\ub098\ub214\uace0\ub515\";")
        self.btnStart = QPushButton(self.tab_1)
        self.btnStart.setObjectName(u"btnStart")
        self.btnStart.setGeometry(QRect(173, 550, 171, 31))
        self.btnStart.setStyleSheet(u"background-color: #f0f0f0;\n"
"border-color: rgb(255, 255, 255);")
        self.btnBrowse = QPushButton(self.tab_1)
        self.btnBrowse.setObjectName(u"btnBrowse")
        self.btnBrowse.setGeometry(QRect(620, 45, 121, 31))
        self.btnBrowse.setStyleSheet(u"background-color: #f0f0f0;")
        self.btnBrowse.setAutoDefault(False)
        self.lblShapeFile_4 = QLabel(self.tab_1)
        self.lblShapeFile_4.setObjectName(u"lblShapeFile_4")
        self.lblShapeFile_4.setGeometry(QRect(20, 329, 201, 21))
        self.lblShapeFile_4.setStyleSheet(u"font: 700 9pt \"\ub9d1\uc740 \uace0\ub515\";")
        self.cmbDepthSelect = QComboBox(self.tab_1)
        self.cmbDepthSelect.setObjectName(u"cmbDepthSelect")
        self.cmbDepthSelect.setGeometry(QRect(150, 240, 281, 31))
        self.label_10 = QLabel(self.tab_1)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(436, 249, 211, 16))
        self.label_10.setStyleSheet(u"font: 9pt \"\ub098\ub214\uace0\ub515\";")
        self.cmbFacilType = QComboBox(self.tab_1)
        self.cmbFacilType.setObjectName(u"cmbFacilType")
        self.cmbFacilType.setGeometry(QRect(150, 10, 151, 31))
        self.label_9 = QLabel(self.tab_1)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(436, 283, 211, 16))
        self.label_9.setStyleSheet(u"font: 9pt \"\ub098\ub214\uace0\ub515\";")
        self.lblShapeFile = QLabel(self.tab_1)
        self.lblShapeFile.setObjectName(u"lblShapeFile")
        self.lblShapeFile.setGeometry(QRect(20, 50, 121, 21))
        self.lblShapeFile.setStyleSheet(u"font: 600 9pt \"\ub098\ub214\uace0\ub515\";")
        self.cmbCircleSeg = QComboBox(self.tab_1)
        self.cmbCircleSeg.setObjectName(u"cmbCircleSeg")
        self.cmbCircleSeg.setGeometry(QRect(150, 353, 281, 31))
        self.ledSaveFolder = QLineEdit(self.tab_1)
        self.ledSaveFolder.setObjectName(u"ledSaveFolder")
        self.ledSaveFolder.setGeometry(QRect(150, 82, 461, 31))
        self.ledSaveFolder.setStyleSheet(u"font: 9pt \"\ub9d1\uc740 \uace0\ub515\";")
        self.ledShapeFile = QLineEdit(self.tab_1)
        self.ledShapeFile.setObjectName(u"ledShapeFile")
        self.ledShapeFile.setGeometry(QRect(150, 45, 461, 31))
        self.ledShapeFile.setStyleSheet(u"font: 9pt \"\ub9d1\uc740 \uace0\ub515\";")
        self.lblShapeFile_3 = QLabel(self.tab_1)
        self.lblShapeFile_3.setObjectName(u"lblShapeFile_3")
        self.lblShapeFile_3.setGeometry(QRect(20, 176, 201, 21))
        self.lblShapeFile_3.setStyleSheet(u"font: 700 9pt \"\ub9d1\uc740 \uace0\ub515\";")
        self.lblResampling = QLabel(self.tab_1)
        self.lblResampling.setObjectName(u"lblResampling")
        self.lblResampling.setGeometry(QRect(20, 394, 116, 16))
        self.lblResampling.setStyleSheet(u"font: 600 9pt \"\ub098\ub214\uace0\ub515\";")
        self.label_13 = QLabel(self.tab_1)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(436, 394, 211, 16))
        self.label_13.setStyleSheet(u"font: 9pt \"\ub098\ub214\uace0\ub515\";")
        self.progressBar = QProgressBar(self.tab_1)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(20, 610, 721, 21))
        self.progressBar.setStyleSheet(u"QProgressBar {\n"
"    border: 1px solid gray;\n"
"    border-radius: 2px;\n"
"    text-align: center;\n"
"    color: black;\n"
"	border-color: rgb(50, 199, 149);\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #05B8CC;\n"
"    width: 20px;\n"
"    margin: 0.5px;\n"
"}")
        self.progressBar.setValue(24)
        self.lblConnectTol = QLabel(self.tab_1)
        self.lblConnectTol.setObjectName(u"lblConnectTol")
        self.lblConnectTol.setGeometry(QRect(20, 427, 116, 16))
        self.lblConnectTol.setStyleSheet(u"font: 600 9pt \"\ub098\ub214\uace0\ub515\";")
        self.label_16 = QLabel(self.tab_1)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(436, 428, 211, 16))
        self.label_16.setStyleSheet(u"font: 9pt \"\ub098\ub214\uace0\ub515\";")
        self.ledConnectTolerance = QLineEdit(self.tab_1)
        self.ledConnectTolerance.setObjectName(u"ledConnectTolerance")
        self.ledConnectTolerance.setGeometry(QRect(150, 419, 281, 31))
        self.ledConnectTolerance.setStyleSheet(u"font: 9pt \"\ub9d1\uc740 \uace0\ub515\";")
        self.lblProgressMsg = QLabel(self.tab_1)
        self.lblProgressMsg.setObjectName(u"lblProgressMsg")
        self.lblProgressMsg.setGeometry(QRect(20, 590, 601, 16))
        self.lblProgressMsg.setStyleSheet(u"font: 9pt \"\ub098\ub214\uace0\ub515\";")
        self.cmbFeatureID = QComboBox(self.tab_1)
        self.cmbFeatureID.setObjectName(u"cmbFeatureID")
        self.cmbFeatureID.setGeometry(QRect(150, 205, 281, 31))
        self.lblFearueID = QLabel(self.tab_1)
        self.lblFearueID.setObjectName(u"lblFearueID")
        self.lblFearueID.setGeometry(QRect(20, 212, 116, 16))
        self.lblFearueID.setStyleSheet(u"font: 600 9pt \"\ub098\ub214\uace0\ub515\";")
        self.chkResampleOption_1 = QCheckBox(self.tab_1)
        self.chkResampleOption_1.setObjectName(u"chkResampleOption_1")
        self.chkResampleOption_1.setGeometry(QRect(150, 500, 571, 20))
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.btnSaveFolderBrowse_2 = QPushButton(self.tab_2)
        self.btnSaveFolderBrowse_2.setObjectName(u"btnSaveFolderBrowse_2")
        self.btnSaveFolderBrowse_2.setGeometry(QRect(620, 118, 121, 31))
        self.btnSaveFolderBrowse_2.setStyleSheet(u"background-color: #f0f0f0;")
        self.btnSaveFolderBrowse_2.setAutoDefault(False)
        self.cmbExportFileFormat_2 = QComboBox(self.tab_2)
        self.cmbExportFileFormat_2.setObjectName(u"cmbExportFileFormat_2")
        self.cmbExportFileFormat_2.setGeometry(QRect(150, 507, 281, 31))
        self.lblCircleSeg_2 = QLabel(self.tab_2)
        self.lblCircleSeg_2.setObjectName(u"lblCircleSeg_2")
        self.lblCircleSeg_2.setGeometry(QRect(20, 442, 116, 16))
        self.lblCircleSeg_2.setStyleSheet(u"font: 600 9pt \"\ub098\ub214\uace0\ub515\";")
        self.btnStart_2 = QPushButton(self.tab_2)
        self.btnStart_2.setObjectName(u"btnStart_2")
        self.btnStart_2.setGeometry(QRect(173, 550, 171, 31))
        self.btnStart_2.setStyleSheet(u"background-color: #f0f0f0;\n"
"border-color: rgb(255, 255, 255);")
        self.lblProgressMsg_2 = QLabel(self.tab_2)
        self.lblProgressMsg_2.setObjectName(u"lblProgressMsg_2")
        self.lblProgressMsg_2.setGeometry(QRect(20, 590, 601, 16))
        self.lblProgressMsg_2.setStyleSheet(u"font: 9pt \"\ub098\ub214\uace0\ub515\";")
        self.lblSize_2 = QLabel(self.tab_2)
        self.lblSize_2.setObjectName(u"lblSize_2")
        self.lblSize_2.setGeometry(QRect(20, 286, 91, 16))
        self.lblSize_2.setStyleSheet(u"font: 600 9pt \"\ub098\ub214\uace0\ub515\";")
        self.lblShapeFile_2 = QLabel(self.tab_2)
        self.lblShapeFile_2.setObjectName(u"lblShapeFile_2")
        self.lblShapeFile_2.setGeometry(QRect(20, 50, 121, 21))
        self.lblShapeFile_2.setStyleSheet(u"font: 600 9pt \"\ub098\ub214\uace0\ub515\";")
        self.btnBrowse_2 = QPushButton(self.tab_2)
        self.btnBrowse_2.setObjectName(u"btnBrowse_2")
        self.btnBrowse_2.setGeometry(QRect(620, 45, 121, 31))
        self.btnBrowse_2.setStyleSheet(u"background-color: #f0f0f0;")
        self.btnBrowse_2.setAutoDefault(False)
        self.lblExportFile_2 = QLabel(self.tab_2)
        self.lblExportFile_2.setObjectName(u"lblExportFile_2")
        self.lblExportFile_2.setGeometry(QRect(20, 514, 116, 16))
        self.lblExportFile_2.setStyleSheet(u"font: 600 9pt \"\ub098\ub214\uace0\ub515\";")
        self.lblConnectTol_2 = QLabel(self.tab_2)
        self.lblConnectTol_2.setObjectName(u"lblConnectTol_2")
        self.lblConnectTol_2.setGeometry(QRect(20, 477, 116, 16))
        self.lblConnectTol_2.setStyleSheet(u"font: 600 9pt \"\ub098\ub214\uace0\ub515\";")
        self.btnApply_2 = QPushButton(self.tab_2)
        self.btnApply_2.setObjectName(u"btnApply_2")
        self.btnApply_2.setGeometry(QRect(290, 162, 171, 31))
        self.btnApply_2.setStyleSheet(u"background-color: #f0f0f0;\n"
"border-color: rgb(255, 255, 255);")
        self.ledShapeFile_2 = QLineEdit(self.tab_2)
        self.ledShapeFile_2.setObjectName(u"ledShapeFile_2")
        self.ledShapeFile_2.setGeometry(QRect(150, 45, 461, 31))
        self.ledShapeFile_2.setStyleSheet(u"font: 9pt \"\ub9d1\uc740 \uace0\ub515\";")
        self.label_11 = QLabel(self.tab_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(370, 254, 71, 16))
        self.label_11.setStyleSheet(u"font: 9pt \"\ub098\ub214\uace0\ub515\";")
        self.line_3 = QFrame(self.tab_2)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(20, 198, 721, 20))
        self.line_3.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.line_3.setFrameShape(QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QFrame.Shadow.Sunken)
        self.lblStartDepth_2 = QLabel(self.tab_2)
        self.lblStartDepth_2.setObjectName(u"lblStartDepth_2")
        self.lblStartDepth_2.setGeometry(QRect(20, 251, 91, 16))
        self.lblStartDepth_2.setStyleSheet(u"font: 600 9pt \"\ub098\ub214\uace0\ub515\";")
        self.lblShapeFile_5 = QLabel(self.tab_2)
        self.lblShapeFile_5.setObjectName(u"lblShapeFile_5")
        self.lblShapeFile_5.setGeometry(QRect(20, 410, 201, 21))
        self.lblShapeFile_5.setStyleSheet(u"font: 700 9pt \"\ub9d1\uc740 \uace0\ub515\";")
        self.cmbCircleSeg_2 = QComboBox(self.tab_2)
        self.cmbCircleSeg_2.setObjectName(u"cmbCircleSeg_2")
        self.cmbCircleSeg_2.setGeometry(QRect(150, 435, 281, 31))
        self.label_12 = QLabel(self.tab_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(370, 288, 71, 16))
        self.label_12.setStyleSheet(u"font: 9pt \"\ub098\ub214\uace0\ub515\";")
        self.btnStop_2 = QPushButton(self.tab_2)
        self.btnStop_2.setObjectName(u"btnStop_2")
        self.btnStop_2.setGeometry(QRect(413, 550, 171, 31))
        self.btnStop_2.setStyleSheet(u"background-color: #f0f0f0;\n"
"border-color: rgb(255, 255, 255);")
        self.ledConnectTolerance_2 = QLineEdit(self.tab_2)
        self.ledConnectTolerance_2.setObjectName(u"ledConnectTolerance_2")
        self.ledConnectTolerance_2.setGeometry(QRect(150, 470, 281, 31))
        self.ledConnectTolerance_2.setStyleSheet(u"font: 9pt \"\ub9d1\uc740 \uace0\ub515\";")
        self.progressBar_2 = QProgressBar(self.tab_2)
        self.progressBar_2.setObjectName(u"progressBar_2")
        self.progressBar_2.setGeometry(QRect(20, 610, 721, 21))
        self.progressBar_2.setStyleSheet(u"QProgressBar {\n"
"    border: 1px solid gray;\n"
"    border-radius: 2px;\n"
"    text-align: center;\n"
"    color: black;\n"
"	border-color: rgb(50, 199, 149);\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #05B8CC;\n"
"    width: 20px;\n"
"    margin: 0.5px;\n"
"}")
        self.progressBar_2.setValue(24)
        self.lblShapeFile_6 = QLabel(self.tab_2)
        self.lblShapeFile_6.setObjectName(u"lblShapeFile_6")
        self.lblShapeFile_6.setGeometry(QRect(20, 219, 201, 21))
        self.lblShapeFile_6.setStyleSheet(u"font: 700 9pt \"\ub9d1\uc740 \uace0\ub515\";")
        self.lblSaveFolder_2 = QLabel(self.tab_2)
        self.lblSaveFolder_2.setObjectName(u"lblSaveFolder_2")
        self.lblSaveFolder_2.setGeometry(QRect(20, 123, 121, 21))
        self.lblSaveFolder_2.setStyleSheet(u"font: 600 9pt \"\ub098\ub214\uace0\ub515\";")
        self.ledSaveFolder_2 = QLineEdit(self.tab_2)
        self.ledSaveFolder_2.setObjectName(u"ledSaveFolder_2")
        self.ledSaveFolder_2.setGeometry(QRect(150, 118, 461, 31))
        self.ledSaveFolder_2.setStyleSheet(u"font: 9pt \"\ub9d1\uc740 \uace0\ub515\";")
        self.cmbSizeSelect_2 = QComboBox(self.tab_2)
        self.cmbSizeSelect_2.setObjectName(u"cmbSizeSelect_2")
        self.cmbSizeSelect_2.setGeometry(QRect(114, 279, 251, 31))
        self.cmbAvrgDepthSelect = QComboBox(self.tab_2)
        self.cmbAvrgDepthSelect.setObjectName(u"cmbAvrgDepthSelect")
        self.cmbAvrgDepthSelect.setGeometry(QRect(114, 244, 251, 31))
        self.label_17 = QLabel(self.tab_2)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(436, 479, 211, 16))
        self.label_17.setStyleSheet(u"font: 9pt \"\ub098\ub214\uace0\ub515\";")
        self.line_4 = QFrame(self.tab_2)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(20, 386, 721, 20))
        self.line_4.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.line_4.setFrameShape(QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_15 = QLabel(self.tab_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(370, 323, 71, 16))
        self.label_15.setStyleSheet(u"font: 9pt \"\ub098\ub214\uace0\ub515\";")
        self.lblStartDepth_4 = QLabel(self.tab_2)
        self.lblStartDepth_4.setObjectName(u"lblStartDepth_4")
        self.lblStartDepth_4.setGeometry(QRect(20, 320, 91, 16))
        self.lblStartDepth_4.setStyleSheet(u"font: 600 9pt \"\ub098\ub214\uace0\ub515\";")
        self.cmbPointDepthSelect = QComboBox(self.tab_2)
        self.cmbPointDepthSelect.setObjectName(u"cmbPointDepthSelect")
        self.cmbPointDepthSelect.setGeometry(QRect(114, 313, 251, 31))
        self.ledPointShapeFile = QLineEdit(self.tab_2)
        self.ledPointShapeFile.setObjectName(u"ledPointShapeFile")
        self.ledPointShapeFile.setGeometry(QRect(150, 82, 461, 31))
        self.ledPointShapeFile.setStyleSheet(u"font: 9pt \"\ub9d1\uc740 \uace0\ub515\";")
        self.lblShapeFile_10 = QLabel(self.tab_2)
        self.lblShapeFile_10.setObjectName(u"lblShapeFile_10")
        self.lblShapeFile_10.setGeometry(QRect(20, 87, 121, 21))
        self.lblShapeFile_10.setStyleSheet(u"font: 600 9pt \"\ub098\ub214\uace0\ub515\";")
        self.btnBrowsePointshp = QPushButton(self.tab_2)
        self.btnBrowsePointshp.setObjectName(u"btnBrowsePointshp")
        self.btnBrowsePointshp.setGeometry(QRect(620, 82, 121, 31))
        self.btnBrowsePointshp.setStyleSheet(u"background-color: #f0f0f0;")
        self.btnBrowsePointshp.setAutoDefault(False)
        self.lblFeatureID_2 = QLabel(self.tab_2)
        self.lblFeatureID_2.setObjectName(u"lblFeatureID_2")
        self.lblFeatureID_2.setGeometry(QRect(460, 251, 81, 16))
        self.lblFeatureID_2.setStyleSheet(u"font: 600 9pt \"\ub098\ub214\uace0\ub515\";")
        self.cmbFeatureID_2 = QComboBox(self.tab_2)
        self.cmbFeatureID_2.setObjectName(u"cmbFeatureID_2")
        self.cmbFeatureID_2.setGeometry(QRect(540, 244, 201, 31))
        self.cmbFacilType_2 = QComboBox(self.tab_2)
        self.cmbFacilType_2.setObjectName(u"cmbFacilType_2")
        self.cmbFacilType_2.setGeometry(QRect(150, 11, 151, 31))
        self.lblFacilName_3 = QLabel(self.tab_2)
        self.lblFacilName_3.setObjectName(u"lblFacilName_3")
        self.lblFacilName_3.setGeometry(QRect(20, 16, 121, 21))
        self.lblFacilName_3.setFont(font)
        self.lblFacilName_3.setStyleSheet(u"font: 600 9pt \"\ub098\ub214\uace0\ub515\";")
        self.btnGDFExport = QPushButton(self.tab_2)
        self.btnGDFExport.setObjectName(u"btnGDFExport")
        self.btnGDFExport.setGeometry(QRect(270, 350, 211, 31))
        self.btnGDFExport.setStyleSheet(u"background-color: #f0f0f0;\n"
"border-color: rgb(255, 255, 255);")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.cmbExportFileFormat_3 = QComboBox(self.tab_3)
        self.cmbExportFileFormat_3.setObjectName(u"cmbExportFileFormat_3")
        self.cmbExportFileFormat_3.setGeometry(QRect(150, 476, 281, 31))
        self.btnBrowse_3 = QPushButton(self.tab_3)
        self.btnBrowse_3.setObjectName(u"btnBrowse_3")
        self.btnBrowse_3.setGeometry(QRect(620, 45, 121, 31))
        self.btnBrowse_3.setStyleSheet(u"background-color: #f0f0f0;")
        self.btnBrowse_3.setAutoDefault(False)
        self.lblStartDepth_3 = QLabel(self.tab_3)
        self.lblStartDepth_3.setObjectName(u"lblStartDepth_3")
        self.lblStartDepth_3.setGeometry(QRect(20, 206, 81, 16))
        self.lblStartDepth_3.setStyleSheet(u"font: 600 9pt \"\ub098\ub214\uace0\ub515\";")
        self.lblFacilName_4 = QLabel(self.tab_3)
        self.lblFacilName_4.setObjectName(u"lblFacilName_4")
        self.lblFacilName_4.setGeometry(QRect(20, 17, 121, 21))
        self.lblFacilName_4.setFont(font)
        self.lblFacilName_4.setStyleSheet(u"font: 600 9pt \"\ub098\ub214\uace0\ub515\";")
        self.cmbSizeSelect_3 = QComboBox(self.tab_3)
        self.cmbSizeSelect_3.setObjectName(u"cmbSizeSelect_3")
        self.cmbSizeSelect_3.setGeometry(QRect(110, 234, 231, 31))
        self.label_21 = QLabel(self.tab_3)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(436, 450, 211, 16))
        self.label_21.setStyleSheet(u"font: 9pt \"\ub098\ub214\uace0\ub515\";")
        self.cmbResamplingIntervals_3 = QComboBox(self.tab_3)
        self.cmbResamplingIntervals_3.setObjectName(u"cmbResamplingIntervals_3")
        self.cmbResamplingIntervals_3.setGeometry(QRect(150, 409, 281, 31))
        self.line_5 = QFrame(self.tab_3)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(20, 151, 721, 20))
        self.line_5.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.line_5.setFrameShape(QFrame.Shape.HLine)
        self.line_5.setFrameShadow(QFrame.Shadow.Sunken)
        self.lblShapeFile_8 = QLabel(self.tab_3)
        self.lblShapeFile_8.setObjectName(u"lblShapeFile_8")
        self.lblShapeFile_8.setGeometry(QRect(20, 352, 201, 21))
        self.lblShapeFile_8.setStyleSheet(u"font: 700 9pt \"\ub9d1\uc740 \uace0\ub515\";")
        self.cmbStartDepthSelect = QComboBox(self.tab_3)
        self.cmbStartDepthSelect.setObjectName(u"cmbStartDepthSelect")
        self.cmbStartDepthSelect.setGeometry(QRect(110, 199, 231, 31))
        self.label_18 = QLabel(self.tab_3)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(690, 208, 71, 16))
        self.label_18.setStyleSheet(u"font: 9pt \"\ub098\ub214\uace0\ub515\";")
        self.lblCircleSeg_3 = QLabel(self.tab_3)
        self.lblCircleSeg_3.setObjectName(u"lblCircleSeg_3")
        self.lblCircleSeg_3.setGeometry(QRect(20, 383, 116, 16))
        self.lblCircleSeg_3.setStyleSheet(u"font: 600 9pt \"\ub098\ub214\uace0\ub515\";")
        self.lblResampling_3 = QLabel(self.tab_3)
        self.lblResampling_3.setObjectName(u"lblResampling_3")
        self.lblResampling_3.setGeometry(QRect(20, 417, 116, 16))
        self.lblResampling_3.setStyleSheet(u"font: 600 9pt \"\ub098\ub214\uace0\ub515\";")
        self.line_6 = QFrame(self.tab_3)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(20, 333, 721, 20))
        self.line_6.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.line_6.setFrameShape(QFrame.Shape.HLine)
        self.line_6.setFrameShadow(QFrame.Shadow.Sunken)
        self.lblShapeFile_9 = QLabel(self.tab_3)
        self.lblShapeFile_9.setObjectName(u"lblShapeFile_9")
        self.lblShapeFile_9.setGeometry(QRect(20, 171, 201, 21))
        self.lblShapeFile_9.setStyleSheet(u"font: 700 9pt \"\ub9d1\uc740 \uace0\ub515\";")
        self.ledShapeFile_3 = QLineEdit(self.tab_3)
        self.ledShapeFile_3.setObjectName(u"ledShapeFile_3")
        self.ledShapeFile_3.setGeometry(QRect(150, 45, 461, 31))
        self.ledShapeFile_3.setStyleSheet(u"font: 9pt \"\ub9d1\uc740 \uace0\ub515\";")
        self.btnSaveFolderBrowse_3 = QPushButton(self.tab_3)
        self.btnSaveFolderBrowse_3.setObjectName(u"btnSaveFolderBrowse_3")
        self.btnSaveFolderBrowse_3.setGeometry(QRect(620, 82, 121, 31))
        self.btnSaveFolderBrowse_3.setStyleSheet(u"background-color: #f0f0f0;")
        self.btnSaveFolderBrowse_3.setAutoDefault(False)
        self.btnStop_3 = QPushButton(self.tab_3)
        self.btnStop_3.setObjectName(u"btnStop_3")
        self.btnStop_3.setGeometry(QRect(413, 550, 171, 31))
        self.btnStop_3.setStyleSheet(u"background-color: #f0f0f0;\n"
"border-color: rgb(255, 255, 255);")
        self.lblProgressMsg_3 = QLabel(self.tab_3)
        self.lblProgressMsg_3.setObjectName(u"lblProgressMsg_3")
        self.lblProgressMsg_3.setGeometry(QRect(20, 590, 601, 16))
        self.lblProgressMsg_3.setStyleSheet(u"font: 9pt \"\ub098\ub214\uace0\ub515\";")
        self.ledConnectTolerance_3 = QLineEdit(self.tab_3)
        self.ledConnectTolerance_3.setObjectName(u"ledConnectTolerance_3")
        self.ledConnectTolerance_3.setGeometry(QRect(150, 441, 281, 31))
        self.ledConnectTolerance_3.setStyleSheet(u"font: 9pt \"\ub9d1\uc740 \uace0\ub515\";")
        self.progressBar_3 = QProgressBar(self.tab_3)
        self.progressBar_3.setObjectName(u"progressBar_3")
        self.progressBar_3.setGeometry(QRect(20, 610, 721, 21))
        self.progressBar_3.setStyleSheet(u"QProgressBar {\n"
"    border: 1px solid gray;\n"
"    border-radius: 2px;\n"
"    text-align: center;\n"
"    color: black;\n"
"	border-color: rgb(50, 199, 149);\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #05B8CC;\n"
"    width: 20px;\n"
"    margin: 0.5px;\n"
"}")
        self.progressBar_3.setValue(24)
        self.lblSaveFolder_3 = QLabel(self.tab_3)
        self.lblSaveFolder_3.setObjectName(u"lblSaveFolder_3")
        self.lblSaveFolder_3.setGeometry(QRect(20, 87, 121, 21))
        self.lblSaveFolder_3.setStyleSheet(u"font: 600 9pt \"\ub098\ub214\uace0\ub515\";")
        self.label_19 = QLabel(self.tab_3)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(436, 416, 211, 16))
        self.label_19.setStyleSheet(u"font: 9pt \"\ub098\ub214\uace0\ub515\";")
        self.cmbCircleSeg_3 = QComboBox(self.tab_3)
        self.cmbCircleSeg_3.setObjectName(u"cmbCircleSeg_3")
        self.cmbCircleSeg_3.setGeometry(QRect(150, 375, 281, 31))
        self.ledSaveFolder_3 = QLineEdit(self.tab_3)
        self.ledSaveFolder_3.setObjectName(u"ledSaveFolder_3")
        self.ledSaveFolder_3.setGeometry(QRect(150, 82, 461, 31))
        self.ledSaveFolder_3.setStyleSheet(u"font: 9pt \"\ub9d1\uc740 \uace0\ub515\";")
        self.lblSize_3 = QLabel(self.tab_3)
        self.lblSize_3.setObjectName(u"lblSize_3")
        self.lblSize_3.setGeometry(QRect(20, 241, 71, 16))
        self.lblSize_3.setStyleSheet(u"font: 600 9pt \"\ub098\ub214\uace0\ub515\";")
        self.btnStart_3 = QPushButton(self.tab_3)
        self.btnStart_3.setObjectName(u"btnStart_3")
        self.btnStart_3.setGeometry(QRect(173, 550, 171, 31))
        self.btnStart_3.setStyleSheet(u"background-color: #f0f0f0;\n"
"border-color: rgb(255, 255, 255);")
        self.btnApply_3 = QPushButton(self.tab_3)
        self.btnApply_3.setObjectName(u"btnApply_3")
        self.btnApply_3.setGeometry(QRect(290, 120, 171, 31))
        self.btnApply_3.setStyleSheet(u"background-color: #f0f0f0;\n"
"border-color: rgb(255, 255, 255);")
        self.lblExportFile_3 = QLabel(self.tab_3)
        self.lblExportFile_3.setObjectName(u"lblExportFile_3")
        self.lblExportFile_3.setGeometry(QRect(20, 483, 116, 16))
        self.lblExportFile_3.setStyleSheet(u"font: 600 9pt \"\ub098\ub214\uace0\ub515\";")
        self.lblConnectTol_3 = QLabel(self.tab_3)
        self.lblConnectTol_3.setObjectName(u"lblConnectTol_3")
        self.lblConnectTol_3.setGeometry(QRect(20, 450, 116, 16))
        self.lblConnectTol_3.setStyleSheet(u"font: 600 9pt \"\ub098\ub214\uace0\ub515\";")
        self.cmbFacilType_3 = QComboBox(self.tab_3)
        self.cmbFacilType_3.setObjectName(u"cmbFacilType_3")
        self.cmbFacilType_3.setGeometry(QRect(150, 10, 151, 31))
        self.lblShapeFile_7 = QLabel(self.tab_3)
        self.lblShapeFile_7.setObjectName(u"lblShapeFile_7")
        self.lblShapeFile_7.setGeometry(QRect(20, 50, 121, 21))
        self.lblShapeFile_7.setStyleSheet(u"font: 600 9pt \"\ub098\ub214\uace0\ub515\";")
        self.cmbEndDepthSelect = QComboBox(self.tab_3)
        self.cmbEndDepthSelect.setObjectName(u"cmbEndDepthSelect")
        self.cmbEndDepthSelect.setGeometry(QRect(450, 199, 231, 31))
        self.lblStartDepth_5 = QLabel(self.tab_3)
        self.lblStartDepth_5.setObjectName(u"lblStartDepth_5")
        self.lblStartDepth_5.setGeometry(QRect(360, 206, 81, 16))
        self.lblStartDepth_5.setStyleSheet(u"font: 600 9pt \"\ub098\ub214\uace0\ub515\";")
        self.lblStartDepth_6 = QLabel(self.tab_3)
        self.lblStartDepth_6.setObjectName(u"lblStartDepth_6")
        self.lblStartDepth_6.setGeometry(QRect(20, 276, 71, 16))
        self.lblStartDepth_6.setStyleSheet(u"font: 600 9pt \"\ub098\ub214\uace0\ub515\";")
        self.cmbHightSelect = QComboBox(self.tab_3)
        self.cmbHightSelect.setObjectName(u"cmbHightSelect")
        self.cmbHightSelect.setGeometry(QRect(450, 269, 231, 31))
        self.cmbWidthSelect = QComboBox(self.tab_3)
        self.cmbWidthSelect.setObjectName(u"cmbWidthSelect")
        self.cmbWidthSelect.setGeometry(QRect(110, 269, 231, 31))
        self.lblStartDepth_7 = QLabel(self.tab_3)
        self.lblStartDepth_7.setObjectName(u"lblStartDepth_7")
        self.lblStartDepth_7.setGeometry(QRect(360, 276, 81, 16))
        self.lblStartDepth_7.setStyleSheet(u"font: 600 9pt \"\ub098\ub214\uace0\ub515\";")
        self.label_22 = QLabel(self.tab_3)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(690, 278, 71, 16))
        self.label_22.setStyleSheet(u"font: 9pt \"\ub098\ub214\uace0\ub515\";")
        self.lblPipeRow = QLabel(self.tab_3)
        self.lblPipeRow.setObjectName(u"lblPipeRow")
        self.lblPipeRow.setGeometry(QRect(360, 241, 71, 16))
        self.lblPipeRow.setStyleSheet(u"font: 600 9pt \"\ub098\ub214\uace0\ub515\";")
        self.cmbPipeRow = QComboBox(self.tab_3)
        self.cmbPipeRow.setObjectName(u"cmbPipeRow")
        self.cmbPipeRow.setGeometry(QRect(450, 234, 231, 31))
        self.cmbFeatureID_3 = QComboBox(self.tab_3)
        self.cmbFeatureID_3.setObjectName(u"cmbFeatureID_3")
        self.cmbFeatureID_3.setGeometry(QRect(110, 303, 231, 31))
        self.lblFeatureID_3 = QLabel(self.tab_3)
        self.lblFeatureID_3.setObjectName(u"lblFeatureID_3")
        self.lblFeatureID_3.setGeometry(QRect(20, 310, 81, 16))
        self.lblFeatureID_3.setStyleSheet(u"font: 600 9pt \"\ub098\ub214\uace0\ub515\";")
        self.chkResampleOption_3 = QCheckBox(self.tab_3)
        self.chkResampleOption_3.setObjectName(u"chkResampleOption_3")
        self.chkResampleOption_3.setGeometry(QRect(150, 520, 571, 20))
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.horizontalLayoutWidget = QWidget(self.tab_4)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(20, 19, 731, 31))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.label = QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName(u"label")

        self.horizontalLayout.addWidget(self.label)

        self.leWorkspaceFolder = QLineEdit(self.horizontalLayoutWidget)
        self.leWorkspaceFolder.setObjectName(u"leWorkspaceFolder")

        self.horizontalLayout.addWidget(self.leWorkspaceFolder)

        self.btWorkFolderBrowse = QPushButton(self.horizontalLayoutWidget)
        self.btWorkFolderBrowse.setObjectName(u"btWorkFolderBrowse")

        self.horizontalLayout.addWidget(self.btWorkFolderBrowse)

        self.verticalLayoutWidget = QWidget(self.tab_4)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(20, 160, 291, 341))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(10, 5, 10, 0)
        self.label_2 = QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName(u"label_2")

        self.verticalLayout.addWidget(self.label_2)

        self.lwGpkgFileList = QListWidget(self.verticalLayoutWidget)
        self.lwGpkgFileList.setObjectName(u"lwGpkgFileList")

        self.verticalLayout.addWidget(self.lwGpkgFileList)

        self.verticalLayoutWidget_2 = QWidget(self.tab_4)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(330, 250, 111, 161))
        self.verticalLayout_2 = QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.btAllFilesAdd = QPushButton(self.verticalLayoutWidget_2)
        self.btAllFilesAdd.setObjectName(u"btAllFilesAdd")

        self.verticalLayout_2.addWidget(self.btAllFilesAdd)

        self.btSelectedFilesAdd = QPushButton(self.verticalLayoutWidget_2)
        self.btSelectedFilesAdd.setObjectName(u"btSelectedFilesAdd")

        self.verticalLayout_2.addWidget(self.btSelectedFilesAdd)

        self.btRemoveSelected = QPushButton(self.verticalLayoutWidget_2)
        self.btRemoveSelected.setObjectName(u"btRemoveSelected")

        self.verticalLayout_2.addWidget(self.btRemoveSelected)

        self.btRemoveAll = QPushButton(self.verticalLayoutWidget_2)
        self.btRemoveAll.setObjectName(u"btRemoveAll")

        self.verticalLayout_2.addWidget(self.btRemoveAll)

        self.btGdfListOpen = QPushButton(self.tab_4)
        self.btGdfListOpen.setObjectName(u"btGdfListOpen")
        self.btGdfListOpen.setGeometry(QRect(290, 100, 201, 31))
        self.verticalLayoutWidget_3 = QWidget(self.tab_4)
        self.verticalLayoutWidget_3.setObjectName(u"verticalLayoutWidget_3")
        self.verticalLayoutWidget_3.setGeometry(QRect(460, 160, 291, 341))
        self.verticalLayout_3 = QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(10, 5, 10, 0)
        self.label_3 = QLabel(self.verticalLayoutWidget_3)
        self.label_3.setObjectName(u"label_3")

        self.verticalLayout_3.addWidget(self.label_3)

        self.lwAnalysisFileList = QListWidget(self.verticalLayoutWidget_3)
        self.lwAnalysisFileList.setObjectName(u"lwAnalysisFileList")

        self.verticalLayout_3.addWidget(self.lwAnalysisFileList)

        self.horizontalLayoutWidget_2 = QWidget(self.tab_4)
        self.horizontalLayoutWidget_2.setObjectName(u"horizontalLayoutWidget_2")
        self.horizontalLayoutWidget_2.setGeometry(QRect(20, 50, 731, 31))
        self.horizontalLayout_2 = QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_4 = QLabel(self.horizontalLayoutWidget_2)
        self.label_4.setObjectName(u"label_4")

        self.horizontalLayout_2.addWidget(self.label_4)

        self.leSourceFolder = QLineEdit(self.horizontalLayoutWidget_2)
        self.leSourceFolder.setObjectName(u"leSourceFolder")

        self.horizontalLayout_2.addWidget(self.leSourceFolder)

        self.btSourceFolderBrowse = QPushButton(self.horizontalLayoutWidget_2)
        self.btSourceFolderBrowse.setObjectName(u"btSourceFolderBrowse")

        self.horizontalLayout_2.addWidget(self.btSourceFolderBrowse)

        self.btAnalysisWorkStart = QPushButton(self.tab_4)
        self.btAnalysisWorkStart.setObjectName(u"btAnalysisWorkStart")
        self.btAnalysisWorkStart.setGeometry(QRect(150, 520, 201, 31))
        self.btAnalysisWorkStop = QPushButton(self.tab_4)
        self.btAnalysisWorkStop.setObjectName(u"btAnalysisWorkStop")
        self.btAnalysisWorkStop.setGeometry(QRect(420, 520, 201, 31))
        self.verticalLayoutWidget_4 = QWidget(self.tab_4)
        self.verticalLayoutWidget_4.setObjectName(u"verticalLayoutWidget_4")
        self.verticalLayoutWidget_4.setGeometry(QRect(20, 560, 731, 80))
        self.verticalLayout_4 = QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.label_5 = QLabel(self.verticalLayoutWidget_4)
        self.label_5.setObjectName(u"label_5")

        self.verticalLayout_4.addWidget(self.label_5)

        self.teAnalysisResults = QPlainTextEdit(self.verticalLayoutWidget_4)
        self.teAnalysisResults.setObjectName(u"teAnalysisResults")

        self.verticalLayout_4.addWidget(self.teAnalysisResults)

        self.tabWidget.addTab(self.tab_4, "")
        self.btnClose = QPushButton(self.centralwidget)
        self.btnClose.setObjectName(u"btnClose")
        self.btnClose.setGeometry(QRect(580, 780, 171, 31))
        self.btnClose.setStyleSheet(u"background-color: #f0f0f0;\n"
"border-color: rgb(255, 255, 255);")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 772, 33))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menuFile.addAction(self.actionWorkspace)
        self.menuFile.addAction(self.actionDBF_Schema)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(3)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"3D Converter for 2D Shape", None))
        self.actionWorkspace.setText(QCoreApplication.translate("MainWindow", u"Workspace", None))
        self.actionDBF_Schema.setText(QCoreApplication.translate("MainWindow", u"Feature Attribute Field ..", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.lblCircleSeg.setText(QCoreApplication.translate("MainWindow", u"\uc6d0\ud615 \ub2e8\uba74 \ubd84\ud560 \uac2f\uc218 :", None))
        self.lblFacilName.setText(QCoreApplication.translate("MainWindow", u"\uc2dc\uc124\ubb3c \uc885\ub958", None))
        self.btnStop.setText(QCoreApplication.translate("MainWindow", u"\ubcc0\ud658 \uc911\uc9c0", None))
        self.cmbExportFileFormat.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\ub0b4\ubcf4\ub0bc \ud30c\uc77c \ud615\uc2dd\uc744 \uc120\ud0dd\ud558\uc5ec \uc8fc\uc138\uc694", None))
        self.cmbResamplingIntervals.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\uc120\ud615 \uc911\uac04\uc810 \uac04\uaca9\uc744 \uc124\uc815\ud558\uc5ec \uc8fc\uc138\uc694", None))
        self.btnApply.setText(QCoreApplication.translate("MainWindow", u"\uc801\uc6a9", None))
        self.lblSaveFolder.setText(QCoreApplication.translate("MainWindow", u"\uc800\uc7a5 \ud3f4\ub354 :", None))
        self.lblSize.setText(QCoreApplication.translate("MainWindow", u"\ub2e8\uba74\ud06c\uae30(size) :", None))
        self.cmbSizeSelect.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\uad6c\uacbd \ud06c\uae30 \ud56d\ubaa9 \uc120\ud0dd", None))
        self.btnSaveFolderBrowse.setText(QCoreApplication.translate("MainWindow", u"\uc800\uc7a5\ud3f4\ub354 \ubc14\uafb8\uae30", None))
        self.lblStartDepth.setText(QCoreApplication.translate("MainWindow", u"\ud3c9\uade0\uc2ec\ub3c4(z)  :", None))
        self.lblExportFile.setText(QCoreApplication.translate("MainWindow", u"\ub0b4\ubcf4\ub0bc \ud30c\uc77c \ud3ec\ub9f7 :", None))
        self.btnStart.setText(QCoreApplication.translate("MainWindow", u"3D \ubcc0\ud658 \uc2dc\uc791", None))
        self.btnBrowse.setText(QCoreApplication.translate("MainWindow", u"\ud30c\uc77c\ucc3e\uae30...", None))
        self.lblShapeFile_4.setText(QCoreApplication.translate("MainWindow", u">>> 3D \ubcc0\ud658 \uc635\uc158 \uc124\uc815", None))
        self.cmbDepthSelect.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\uae4a\uc774\uac12 \ud56d\ubaa9 \uc120\ud0dd", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"(\ub2e8\uc704 : m)", None))
        self.cmbFacilType.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\uad00\ub85c\uc885\ub958 \uc120\ud0dd", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"(\ub2e8\uc704 : mm)", None))
        self.lblShapeFile.setText(QCoreApplication.translate("MainWindow", u"\uad00\ub85c Shape \ud30c\uc77c :", None))
        self.cmbCircleSeg.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\uc6d0\ud615 \ub2e8\uba74 \ubd84\ud560 \uac2f\uc218\ub97c \uc120\ud0dd\ud558\uc5ec \uc8fc\uc138\uc694", None))
        self.ledSaveFolder.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\uc800\uc7a5 \ud3f4\ub354\ub97c \uc120\ud0dd\ud558\uc5ec \uc8fc\uc138\uc694", None))
        self.ledShapeFile.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\ubcc0\ud658\ud560 shape \ud30c\uc77c\uc744 \uc120\ud0dd\ud558\uc5ec \uc8fc\uc138\uc694", None))
        self.lblShapeFile_3.setText(QCoreApplication.translate("MainWindow", u">>> 3D \ubcc0\ud658\uc6a9 \uc18d\uc131\ud544\ub4dc \uc124\uc815", None))
        self.lblResampling.setText(QCoreApplication.translate("MainWindow", u"\uc911\uac04\uc810 \uac04\uaca9 :", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"(\ub2e8\uc704 : m)", None))
        self.lblConnectTol.setText(QCoreApplication.translate("MainWindow", u"\ub05d\uc810\uc5f0\uacb0 \ud5c8\uc6a9\uc624\ucc28 :", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"(\ub2e8\uc704 : m)", None))
        self.ledConnectTolerance.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\ub05d\uc810 \uc5f0\uacb0 \uc2dc \ud5c8\uc6a9\uc624\ucc28\uac12\uc744 \uc785\ub825\ud558\uc138\uc694", None))
        self.lblProgressMsg.setText(QCoreApplication.translate("MainWindow", u"\ubcc0\ud658\uc791\uc5c5 \ub300\uae30 \uc911 ...", None))
        self.cmbFeatureID.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\uad00\ub85c(Feature) \uc2dd\ubcc4 \ud56d\ubaa9", None))
        self.lblFearueID.setText(QCoreApplication.translate("MainWindow", u"\uad00\ub85c ID :", None))
        self.chkResampleOption_1.setText(QCoreApplication.translate("MainWindow", u"Line Feature \ub0b4 \uc815\uc810\uacfc \uc0bd\uc785\ub41c \uc911\uac04\uc810\uc744 \ubaa8\ub450 \ub9ac\uc0d8\ud50c\ub9c1(\uc911\uac04\uc810\ub9cc \uc801\uc6a9\ud560 \uacbd\uc6b0\ub294 \uc5b8\uccb4\ud06c)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), QCoreApplication.translate("MainWindow", u"\ud3c9\uade0\uc2ec\ub3c4\ubc29\uc2dd        ", None))
        self.btnSaveFolderBrowse_2.setText(QCoreApplication.translate("MainWindow", u"\uc800\uc7a5\ud3f4\ub354 \ubc14\uafb8\uae30", None))
        self.cmbExportFileFormat_2.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\ub0b4\ubcf4\ub0bc \ud30c\uc77c \ud615\uc2dd\uc744 \uc120\ud0dd\ud558\uc5ec \uc8fc\uc138\uc694", None))
        self.lblCircleSeg_2.setText(QCoreApplication.translate("MainWindow", u"\uc6d0\ud615 \ub2e8\uba74 \ubd84\ud560 \uac2f\uc218 :", None))
        self.btnStart_2.setText(QCoreApplication.translate("MainWindow", u"3D \ubcc0\ud658 \uc2dc\uc791", None))
        self.lblProgressMsg_2.setText(QCoreApplication.translate("MainWindow", u"\ubcc0\ud658\uc791\uc5c5 \ub300\uae30 \uc911 ...", None))
        self.lblSize_2.setText(QCoreApplication.translate("MainWindow", u"\ub2e8\uba74\ud06c\uae30(size) :", None))
        self.lblShapeFile_2.setText(QCoreApplication.translate("MainWindow", u"\uad00\ub85c Shape \ud30c\uc77c :", None))
        self.btnBrowse_2.setText(QCoreApplication.translate("MainWindow", u"\ud30c\uc77c\ucc3e\uae30...", None))
        self.lblExportFile_2.setText(QCoreApplication.translate("MainWindow", u"\ub0b4\ubcf4\ub0bc \ud30c\uc77c \ud3ec\ub9f7 :", None))
        self.lblConnectTol_2.setText(QCoreApplication.translate("MainWindow", u"\ub05d\uc810\uc5f0\uacb0 \ud5c8\uc6a9\uc624\ucc28 :", None))
        self.btnApply_2.setText(QCoreApplication.translate("MainWindow", u"\uc801\uc6a9", None))
        self.ledShapeFile_2.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\ubcc0\ud658\ud560 \uad00\ub85c shape \ud30c\uc77c\uc744 \uc120\ud0dd\ud558\uc5ec \uc8fc\uc138\uc694", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"(\ub2e8\uc704 : m)", None))
        self.lblStartDepth_2.setText(QCoreApplication.translate("MainWindow", u"\ud3c9\uade0\uc2ec\ub3c4(z)  :", None))
        self.lblShapeFile_5.setText(QCoreApplication.translate("MainWindow", u">>> 3D \ubcc0\ud658 \uc635\uc158 \uc124\uc815", None))
        self.cmbCircleSeg_2.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\uc6d0\ud615 \ub2e8\uba74 \ubd84\ud560 \uac2f\uc218\ub97c \uc120\ud0dd\ud558\uc5ec \uc8fc\uc138\uc694", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"(\ub2e8\uc704 : mm)", None))
        self.btnStop_2.setText(QCoreApplication.translate("MainWindow", u"\ubcc0\ud658 \uc911\uc9c0", None))
        self.ledConnectTolerance_2.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\ub05d\uc810 \uc5f0\uacb0 \uc2dc \ud5c8\uc6a9\uc624\ucc28\uac12\uc744 \uc785\ub825\ud558\uc138\uc694", None))
        self.lblShapeFile_6.setText(QCoreApplication.translate("MainWindow", u">>> 3D \ubcc0\ud658\uc6a9 \uc18d\uc131\ud544\ub4dc \uc124\uc815", None))
        self.lblSaveFolder_2.setText(QCoreApplication.translate("MainWindow", u"\uc800\uc7a5 \ud3f4\ub354 :", None))
        self.ledSaveFolder_2.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\uc800\uc7a5 \ud3f4\ub354\ub97c \uc120\ud0dd\ud558\uc5ec \uc8fc\uc138\uc694", None))
        self.cmbSizeSelect_2.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\uad6c\uacbd \ud06c\uae30 \ud56d\ubaa9 \uc120\ud0dd", None))
        self.cmbAvrgDepthSelect.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\uae4a\uc774\uac12 \ud56d\ubaa9 \uc120\ud0dd", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"(\ub2e8\uc704 : m)", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"(\ub2e8\uc704 : m)", None))
        self.lblStartDepth_4.setText(QCoreApplication.translate("MainWindow", u"\ud3ec\uc778\ud2b8\uc2ec\ub3c4(z)  :", None))
        self.cmbPointDepthSelect.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\uae4a\uc774\uac12 \ud56d\ubaa9 \uc120\ud0dd", None))
        self.ledPointShapeFile.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\ubcc0\ud658\ud560 \uc2ec\ub3c4 shape \ud30c\uc77c\uc744 \uc120\ud0dd\ud558\uc5ec \uc8fc\uc138\uc694", None))
        self.lblShapeFile_10.setText(QCoreApplication.translate("MainWindow", u"\uc2ec\ub3c4 Shape \ud30c\uc77c :", None))
        self.btnBrowsePointshp.setText(QCoreApplication.translate("MainWindow", u"\ud30c\uc77c\ucc3e\uae30...", None))
        self.lblFeatureID_2.setText(QCoreApplication.translate("MainWindow", u"\uad00\ub85c ID :", None))
        self.cmbFeatureID_2.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\uad00\ub85cID \ud56d\ubaa9 \uc120\ud0dd", None))
        self.cmbFacilType_2.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\uad00\ub85c\uc885\ub958 \uc120\ud0dd", None))
        self.lblFacilName_3.setText(QCoreApplication.translate("MainWindow", u"\uc2dc\uc124\ubb3c \uc885\ub958", None))
        self.btnGDFExport.setText(QCoreApplication.translate("MainWindow", u"GeoDataFrame Export", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"\uc2ec\ub3c4\ud3ec\uc778\ud2b8\uacb0\ud569\ubc29\uc2dd", None))
        self.cmbExportFileFormat_3.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\ub0b4\ubcf4\ub0bc \ud30c\uc77c \ud615\uc2dd\uc744 \uc120\ud0dd\ud558\uc5ec \uc8fc\uc138\uc694", None))
        self.btnBrowse_3.setText(QCoreApplication.translate("MainWindow", u"\ud30c\uc77c\ucc3e\uae30...", None))
        self.lblStartDepth_3.setText(QCoreApplication.translate("MainWindow", u"\uc2dc\uc810\uc2ec\ub3c4(z)  :", None))
        self.lblFacilName_4.setText(QCoreApplication.translate("MainWindow", u"\uc2dc\uc124\ubb3c \uc885\ub958", None))
        self.cmbSizeSelect_3.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\uc6d0\ud615\uad00 \uad6c\uacbd \ud56d\ubaa9 \uc120\ud0dd", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"(\ub2e8\uc704 : m)", None))
        self.cmbResamplingIntervals_3.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\uc120\ud615 \uc911\uac04\uc810 \uac04\uaca9\uc744 \uc124\uc815\ud558\uc5ec \uc8fc\uc138\uc694", None))
        self.lblShapeFile_8.setText(QCoreApplication.translate("MainWindow", u">>> 3D \ubcc0\ud658 \uc635\uc158 \uc124\uc815", None))
        self.cmbStartDepthSelect.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\uc2dc\uc810\uc2ec\ub3c4 \ud56d\ubaa9 \uc120\ud0dd", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"(\ub2e8\uc704 : m)", None))
        self.lblCircleSeg_3.setText(QCoreApplication.translate("MainWindow", u"\uc6d0\ud615 \ub2e8\uba74 \ubd84\ud560 \uac2f\uc218 :", None))
        self.lblResampling_3.setText(QCoreApplication.translate("MainWindow", u"\uc911\uac04\uc810 \uac04\uaca9 :", None))
        self.lblShapeFile_9.setText(QCoreApplication.translate("MainWindow", u">>> 3D \ubcc0\ud658\uc6a9 \uc18d\uc131\ud544\ub4dc \uc124\uc815", None))
        self.ledShapeFile_3.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\ubcc0\ud658\ud560 shape \ud30c\uc77c\uc744 \uc120\ud0dd\ud558\uc5ec \uc8fc\uc138\uc694", None))
        self.btnSaveFolderBrowse_3.setText(QCoreApplication.translate("MainWindow", u"\uc800\uc7a5\ud3f4\ub354 \ubc14\uafb8\uae30", None))
        self.btnStop_3.setText(QCoreApplication.translate("MainWindow", u"\ubcc0\ud658 \uc911\uc9c0", None))
        self.lblProgressMsg_3.setText(QCoreApplication.translate("MainWindow", u"\ubcc0\ud658\uc791\uc5c5 \ub300\uae30 \uc911 ...", None))
        self.ledConnectTolerance_3.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\ub05d\uc810 \uc5f0\uacb0 \uc2dc \ud5c8\uc6a9\uc624\ucc28\uac12\uc744 \uc785\ub825\ud558\uc138\uc694", None))
        self.lblSaveFolder_3.setText(QCoreApplication.translate("MainWindow", u"\uc800\uc7a5 \ud3f4\ub354 :", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"(\ub2e8\uc704 : m)", None))
        self.cmbCircleSeg_3.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\uc6d0\ud615 \ub2e8\uba74 \ubd84\ud560 \uac2f\uc218\ub97c \uc120\ud0dd\ud558\uc5ec \uc8fc\uc138\uc694", None))
        self.ledSaveFolder_3.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\uc800\uc7a5 \ud3f4\ub354\ub97c \uc120\ud0dd\ud558\uc5ec \uc8fc\uc138\uc694", None))
        self.lblSize_3.setText(QCoreApplication.translate("MainWindow", u"\uad6c\uacbd(size) :", None))
        self.btnStart_3.setText(QCoreApplication.translate("MainWindow", u"3D \ubcc0\ud658 \uc2dc\uc791", None))
        self.btnApply_3.setText(QCoreApplication.translate("MainWindow", u"\uc801\uc6a9", None))
        self.lblExportFile_3.setText(QCoreApplication.translate("MainWindow", u"\ub0b4\ubcf4\ub0bc \ud30c\uc77c \ud3ec\ub9f7 :", None))
        self.lblConnectTol_3.setText(QCoreApplication.translate("MainWindow", u"\ub05d\uc810\uc5f0\uacb0 \ud5c8\uc6a9\uc624\ucc28 :", None))
        self.cmbFacilType_3.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\uad00\ub85c\uc885\ub958 \uc120\ud0dd", None))
        self.lblShapeFile_7.setText(QCoreApplication.translate("MainWindow", u"\uad00\ub85c Shape \ud30c\uc77c :", None))
        self.cmbEndDepthSelect.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\uc885\uc810\uc2ec\ub3c4 \ud56d\ubaa9 \uc120\ud0dd", None))
        self.lblStartDepth_5.setText(QCoreApplication.translate("MainWindow", u"\uc885\uc810\uc2ec\ub3c4(z)  :", None))
        self.lblStartDepth_6.setText(QCoreApplication.translate("MainWindow", u"\uac00\ub85c\uae38\uc774 :", None))
        self.cmbHightSelect.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\ubc15\uc2a4\ud615\uad00 \uc138\ub85c\uae38\uc774 \ud56d\ubaa9 \uc120\ud0dd", None))
        self.cmbWidthSelect.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\ubc15\uc2a4\ud615\uad00 \uac00\ub85c\uae38\uc774 \ud56d\ubaa9 \uc120\ud0dd", None))
        self.lblStartDepth_7.setText(QCoreApplication.translate("MainWindow", u"\uc138\ub85c\uae38\uc774 :", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"(\ub2e8\uc704 : m)", None))
        self.lblPipeRow.setText(QCoreApplication.translate("MainWindow", u"\uad00 \uc5f4\uc218 :", None))
        self.cmbPipeRow.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\uad00\uc5f4\uac2f\uc218 \ud56d\ubaa9 \uc120\ud0dd", None))
        self.cmbFeatureID_3.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\uad00\ub85cID \ud56d\ubaa9 \uc120\ud0dd", None))
        self.lblFeatureID_3.setText(QCoreApplication.translate("MainWindow", u"\uad00\ub85c ID :", None))
        self.chkResampleOption_3.setText(QCoreApplication.translate("MainWindow", u"Line Feature \ub0b4 \uc815\uc810\uacfc \uc0bd\uc785\ub41c \uc911\uac04\uc810\uc744 \ubaa8\ub450 \ub9ac\uc0d8\ud50c\ub9c1(\uc911\uac04\uc810\ub9cc \uc801\uc6a9\ud560 \uacbd\uc6b0\ub294 \uc5b8\uccb4\ud06c)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"\uc2dc\uc885\uc810\uc2ec\ub3c4(\ud558\uc218)    ", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Workspace Folder :      ", None))
        self.leWorkspaceFolder.setPlaceholderText(QCoreApplication.translate("MainWindow", u"gpkg \ud30c\uc77c\uc774 \uc874\uc7ac\ud558\ub294 \ud3f4\ub354\ub97c \uc120\ud0dd\ud558\uc5ec \uc8fc\uc138\uc694", None))
        self.btWorkFolderBrowse.setText(QCoreApplication.translate("MainWindow", u"     Browse ...     ", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Workspace GeoPackage \ud30c\uc77c", None))
        self.btAllFilesAdd.setText(QCoreApplication.translate("MainWindow", u"\uc804\uccb4 \ucd94\uac00", None))
        self.btSelectedFilesAdd.setText(QCoreApplication.translate("MainWindow", u"\ucd94\uac00 \u25b7\u25b7 ", None))
        self.btRemoveSelected.setText(QCoreApplication.translate("MainWindow", u"\u25c1\u25c1 \uc81c\uc678", None))
        self.btRemoveAll.setText(QCoreApplication.translate("MainWindow", u"\uc804\uccb4 \uc81c\uc678", None))
        self.btGdfListOpen.setText(QCoreApplication.translate("MainWindow", u"\uc791\uc5c5\ud3f4\ub354 gpkg \ubd88\ub7ec\uc624\uae30", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\uac04\uc12d\ubd84\uc11d \ub300\uc0c1 \ud30c\uc77c", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Source Folder :           ", None))
        self.leSourceFolder.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\uc6d0\ubcf8 Shape/DBF \ud30c\uc77c\uc774 \uc788\ub294 \ud3f4\ub354\ub97c \uc120\ud0dd\ud558\uc5ec \uc8fc\uc138\uc694", None))
        self.btSourceFolderBrowse.setText(QCoreApplication.translate("MainWindow", u"     Browse ...     ", None))
        self.btAnalysisWorkStart.setText(QCoreApplication.translate("MainWindow", u"\uac04\uc12d\ubd84\uc11d \uc791\uc5c5 \uc2dc\uc791", None))
        self.btAnalysisWorkStop.setText(QCoreApplication.translate("MainWindow", u"\uac04\uc12d\ubd84\uc11d \uc791\uc5c5 \ucde8\uc18c", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\ubd84\uc11d \uacb0\uacfc", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"\uac04\uc12d\ubd84\uc11d", None))
        self.btnClose.setText(QCoreApplication.translate("MainWindow", u"\ub2eb\uae30", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"Settings", None))
    # retranslateUi

